import { z } from "zod";

export type ApiKind = "resource" | "tool" | "excluded";
export type HttpMethod = "GET" | "POST" | "PATCH" | "DELETE";

export type ApiDefinition = {
  name: string;
  kind: ApiKind;
  method: HttpMethod;
  path: string;
  file: string;
  auth: string;
  description: string;
  requestSchema: string;
  responseSchema: string;
  mappingReason: string;
  excludedReason?: string;
  params?: string[];
  queryKeys?: string[];
  toolSchema?: z.ZodRawShape;
};

const pathParams = (path: string) => [...path.matchAll(/:([A-Za-z0-9_]+)/g)].map((match) => match[1] as string);

const withParams = (definition: Omit<ApiDefinition, "params">): ApiDefinition => ({
  ...definition,
  params: pathParams(definition.path),
});

const qp = z.record(z.union([z.string(), z.number(), z.boolean(), z.null(), z.undefined()])).optional();
const body = z.record(z.string(), z.unknown()).optional();

export const apiDefinitions: ApiDefinition[] = [
  // Platform / server
  withParams({ name: "get_health", kind: "resource", method: "GET", path: "/health", file: "apps/server/src/index.ts", auth: "none", requestSchema: "none", responseSchema: "{ success, message }", description: "Read QuickVoice API health status.", mappingReason: "Read-only health check." }),
  withParams({ name: "get_readiness", kind: "resource", method: "GET", path: "/ready", file: "apps/server/src/index.ts", auth: "none", requestSchema: "none", responseSchema: "{ success, message, data }", description: "Read QuickVoice API readiness including dependent service health.", mappingReason: "Read-only readiness check." }),

  // Agents
  withParams({ name: "list_agents", kind: "resource", method: "GET", path: "/agents", file: "apps/server/src/modules/agent/agent.route.ts", auth: "x-api-key/session; agent:read", requestSchema: "none", responseSchema: "Agent[]", description: "List voice agents in the authenticated organization.", mappingReason: "Read-only list." }),
  withParams({ name: "create_agent", kind: "tool", method: "POST", path: "/agents", file: "apps/server/src/modules/agent/agent.route.ts", auth: "x-api-key/session; agent:create", requestSchema: "{ name: string>=2, isActive: boolean, templateId: uuid|business|medical|blank|support|null }", responseSchema: "Agent", description: "Create a new voice agent. Required body: name, isActive, templateId. Use when a user wants to add a new agent.", mappingReason: "Creates data.", toolSchema: { body } }),
  withParams({ name: "get_voice_catalog", kind: "resource", method: "GET", path: "/agents/voice/catalog", file: "apps/server/src/modules/agent/agent.route.ts", auth: "x-api-key/session; agentConfiguration:read", requestSchema: "none", responseSchema: "VoiceCatalog", description: "Read available languages, STT/LLM/TTS models, voices, defaults, and timezones.", mappingReason: "Read-only catalog." }),
  withParams({ name: "create_agent_preview_session", kind: "tool", method: "POST", path: "/agents/:agentId/preview-session", file: "apps/server/src/modules/agent/agent.route.ts", auth: "x-api-key/session; agentConfiguration:read", requestSchema: "params agentId; body { dynamicVariables?: Record<string,string> }", responseSchema: "AgentPreviewSession", description: "Create a temporary LiveKit preview session for an agent. Required param: agentId. Optional body.dynamicVariables.", mappingReason: "Triggers temporary runtime session.", toolSchema: { agentId: z.string().min(1), body } }),
  withParams({ name: "update_agent", kind: "tool", method: "PATCH", path: "/agents/:id", file: "apps/server/src/modules/agent/agent.route.ts", auth: "x-api-key/session; agent:update", requestSchema: "params id; partial { name, isActive, templateId }", responseSchema: "Agent", description: "Update agent metadata such as name, active state, or template id.", mappingReason: "Mutates agent.", toolSchema: { id: z.string().min(1), body } }),
  withParams({ name: "delete_agent", kind: "tool", method: "DELETE", path: "/agents/:agentId", file: "apps/server/src/modules/agent/agent.route.ts", auth: "x-api-key/session; agent:delete", requestSchema: "params agentId", responseSchema: "null", description: "Delete an agent by id. Use only after confirmation.", mappingReason: "Deletes data.", toolSchema: { agentId: z.string().min(1) } }),
  withParams({ name: "save_agent_config", kind: "tool", method: "POST", path: "/agents/:agentId/config", file: "apps/server/src/modules/agent/agent.route.ts", auth: "x-api-key/session; agentConfiguration:create/update", requestSchema: "params agentId; ConfigureAgentInput", responseSchema: "AgentConfiguration", description: "Create or update a voice agent configuration including first message, system prompt, models, voice, webhooks, variables, RAG, IVR, and timezone.", mappingReason: "Mutates configuration.", toolSchema: { agentId: z.string().min(1), body } }),
  withParams({ name: "get_agent_config", kind: "resource", method: "GET", path: "/agents/:agentId/config", file: "apps/server/src/modules/agent/agent.route.ts", auth: "x-api-key/session; agentConfiguration:read", requestSchema: "params agentId", responseSchema: "AgentConfiguration|null", description: "Read saved configuration for one agent.", mappingReason: "Read-only configuration." }),

  // Calls/dashboard
  withParams({ name: "list_call_logs", kind: "resource", method: "GET", path: "/calls", file: "apps/server/src/modules/calllogs/calllog.route.ts", auth: "x-api-key/session; callLogs:read", requestSchema: "query { agentId?, status?, direction?, from?, to?, limit?, cursor? }", responseSchema: "paginated CallLog[]", description: "List call logs with optional filters.", mappingReason: "Read-only list.", queryKeys: ["agentId", "status", "direction", "from", "to", "limit", "cursor"] }),
  withParams({ name: "list_live_calls", kind: "resource", method: "GET", path: "/calls/live", file: "apps/server/src/modules/calllogs/calllog.route.ts", auth: "x-api-key/session; callLogs:read", requestSchema: "none", responseSchema: "LiveCall[]", description: "List currently live calls.", mappingReason: "Read-only live state." }),
  withParams({ name: "end_live_call", kind: "tool", method: "POST", path: "/calls/live/end", file: "apps/server/src/modules/calllogs/calllog.route.ts", auth: "x-api-key/session; callLogs:delete", requestSchema: "body { roomName }", responseSchema: "result", description: "End a currently live call by LiveKit room name. Use only when the user explicitly wants to terminate a live call.", mappingReason: "Triggers call termination.", toolSchema: { body } }),
  withParams({ name: "get_call_log", kind: "resource", method: "GET", path: "/calls/:callId", file: "apps/server/src/modules/calllogs/calllog.route.ts", auth: "x-api-key/session; callLogs:read", requestSchema: "params callId", responseSchema: "CallLog", description: "Read one call log by call id.", mappingReason: "Read-only detail." }),
  withParams({ name: "list_call_transcripts", kind: "resource", method: "GET", path: "/calls/:callId/transcripts", file: "apps/server/src/modules/calllogs/calllog.route.ts", auth: "x-api-key/session; callLogs:read", requestSchema: "params callId; query { limit?, cursor? }", responseSchema: "paginated CallTranscript[]", description: "Read transcript messages for one call.", mappingReason: "Read-only transcript." }),
  withParams({ name: "delete_call_log", kind: "tool", method: "DELETE", path: "/calls/:callId", file: "apps/server/src/modules/calllogs/calllog.route.ts", auth: "x-api-key/session; callLogs:delete", requestSchema: "params callId", responseSchema: "null", description: "Soft-delete a call log by id. Use only after confirmation.", mappingReason: "Deletes data.", toolSchema: { callId: z.string().min(1) } }),
  withParams({ name: "get_dashboard_summary", kind: "resource", method: "GET", path: "/dashboard/summary", file: "apps/server/src/modules/dashboard/dashboard.route.ts", auth: "x-api-key/session; callLogs:read", requestSchema: "query { range: 24h|7d|30d|custom, from?, to? }", responseSchema: "DashboardSummary", description: "Read dashboard analytics summary for call volume, outcomes, agents, and timeline.", mappingReason: "Read-only analytics.", queryKeys: ["range", "from", "to"] }),

  // Knowledge base
  withParams({ name: "create_knowledge_sources", kind: "tool", method: "POST", path: "/kb", file: "apps/server/src/modules/kb/kb.route.ts", auth: "x-api-key/session; knowledgeSource:create", requestSchema: "body { agentId: uuid, documents: [{ name, sourceType, url?, s3Key?, originalFileName? }] }", responseSchema: "KnowledgeSource[]/job result", description: "Create knowledge sources for an agent from URLs or uploaded files.", mappingReason: "Creates records and triggers ingestion.", toolSchema: { body } }),
  withParams({ name: "list_knowledge_sources", kind: "resource", method: "GET", path: "/kb", file: "apps/server/src/modules/kb/kb.route.ts", auth: "x-api-key/session; knowledgeSource:read", requestSchema: "query { agentId? }", responseSchema: "KnowledgeSource[]", description: "List knowledge base sources, optionally filtered by agent.", mappingReason: "Read-only list.", queryKeys: ["agentId"] }),
  withParams({ name: "get_kb_upload_url", kind: "tool", method: "GET", path: "/kb/upload-url", file: "apps/server/src/modules/kb/kb.route.ts", auth: "x-api-key/session; knowledgeSource:create", requestSchema: "query { fileName, contentType }", responseSchema: "presigned upload URL", description: "Generate a presigned S3 upload URL for a knowledge base file before creating a source.", mappingReason: "Generates a short-lived upload credential.", toolSchema: { query: qp } }),
  withParams({ name: "update_knowledge_source", kind: "tool", method: "PATCH", path: "/kb/:kbId", file: "apps/server/src/modules/kb/kb.route.ts", auth: "x-api-key/session; knowledgeSource:update", requestSchema: "params kbId; body { name?, agentId?, url? }", responseSchema: "KnowledgeSource", description: "Update supported knowledge source fields and queue reprocessing.", mappingReason: "Mutates source configuration and refreshes indexed content.", toolSchema: { kbId: z.string().min(1), body } }),
  withParams({ name: "delete_knowledge_source", kind: "tool", method: "DELETE", path: "/kb/:kbId", file: "apps/server/src/modules/kb/kb.route.ts", auth: "x-api-key/session; knowledgeSource:delete", requestSchema: "params kbId", responseSchema: "null", description: "Delete one knowledge source by id.", mappingReason: "Deletes data.", toolSchema: { kbId: z.string().min(1) } }),

  // Numbers
  withParams({ name: "search_phone_numbers", kind: "resource", method: "GET", path: "/numbers/search", file: "apps/server/src/modules/numbers/phone.route.ts", auth: "x-api-key/session; phoneNumber:create", requestSchema: "query { provider, country, areaCode?, limit? }", responseSchema: "AvailableNumber[]", description: "Search provider inventory for available phone numbers before purchase.", mappingReason: "Read-only provider lookup.", queryKeys: ["provider", "country", "areaCode", "limit"] }),
  withParams({ name: "list_phone_numbers", kind: "resource", method: "GET", path: "/numbers", file: "apps/server/src/modules/numbers/phone.route.ts", auth: "x-api-key/session; phoneNumber:read", requestSchema: "none", responseSchema: "PhoneNumber[]", description: "List phone numbers owned by the organization.", mappingReason: "Read-only list." }),
  withParams({ name: "buy_phone_number", kind: "tool", method: "POST", path: "/numbers", file: "apps/server/src/modules/numbers/phone.route.ts", auth: "x-api-key/session; phoneNumber:create", requestSchema: "body { provider, phoneNumber: E.164 }", responseSchema: "PhoneNumber", description: "Purchase a phone number from the selected provider. Use only after the user chooses a number.", mappingReason: "Purchases external resource.", toolSchema: { body } }),
  withParams({ name: "assign_phone_number", kind: "tool", method: "PATCH", path: "/numbers/:phId", file: "apps/server/src/modules/numbers/phone.route.ts", auth: "x-api-key/session; phoneNumber:update", requestSchema: "params phId; body { agentId: uuid|null }", responseSchema: "PhoneNumber", description: "Assign or unassign a phone number to/from an agent.", mappingReason: "Mutates phone routing.", toolSchema: { phId: z.string().min(1), body } }),
  withParams({ name: "delete_phone_number", kind: "tool", method: "DELETE", path: "/numbers/:phId", file: "apps/server/src/modules/numbers/phone.route.ts", auth: "x-api-key/session; phoneNumber:delete", requestSchema: "params phId", responseSchema: "null", description: "Delete/release an organization phone number.", mappingReason: "Deletes external/resource record.", toolSchema: { phId: z.string().min(1) } }),

  // Outbound
  withParams({ name: "list_outbound_calls", kind: "resource", method: "GET", path: "/outbound-calls", file: "apps/server/src/modules/outbound/outbound-call.route.ts", auth: "x-api-key/session; outboundCalls:read", requestSchema: "query { agentId?, status?, mode?, limit?, cursor? }", responseSchema: "paginated OutboundCall[]", description: "List outbound calls with optional filters.", mappingReason: "Read-only list.", queryKeys: ["agentId", "status", "mode", "limit", "cursor"] }),
  withParams({ name: "create_quick_outbound_call", kind: "tool", method: "POST", path: "/outbound-calls/quick", file: "apps/server/src/modules/outbound/outbound-call.route.ts", auth: "x-api-key/session; outboundCalls:create", requestSchema: "body quickOutboundCallSchema", responseSchema: "OutboundCall", description: "Dispatch a single outbound call for an agent to a phone number.", mappingReason: "Triggers outbound call.", toolSchema: { body } }),
  withParams({ name: "create_batch_upload_url", kind: "tool", method: "GET", path: "/outbound-calls/batch-upload-url", file: "apps/server/src/modules/outbound/outbound-call.route.ts", auth: "x-api-key/session; outboundCalls:create", requestSchema: "query { fileName csv|xlsx, contentType }", responseSchema: "presigned upload URL", description: "Generate presigned upload URL for outbound batch CSV/XLSX file.", mappingReason: "Generates short-lived upload credential.", toolSchema: { query: qp } }),
  withParams({ name: "create_batch_campaign", kind: "tool", method: "POST", path: "/outbound-calls/batches", file: "apps/server/src/modules/outbound/outbound-call.route.ts", auth: "x-api-key/session; outboundCalls:create", requestSchema: "body createBatchCampaignSchema", responseSchema: "BatchCampaign", description: "Create an outbound batch campaign from an uploaded CSV/XLSX source file.", mappingReason: "Creates campaign.", toolSchema: { body } }),
  withParams({ name: "list_batch_campaigns", kind: "resource", method: "GET", path: "/outbound-calls/batches", file: "apps/server/src/modules/outbound/outbound-call.route.ts", auth: "x-api-key/session; outboundCalls:read", requestSchema: "query { agentId? }", responseSchema: "BatchCampaign[]", description: "List outbound batch campaigns.", mappingReason: "Read-only list.", queryKeys: ["agentId"] }),
  withParams({ name: "get_batch_campaign", kind: "resource", method: "GET", path: "/outbound-calls/batches/:campaignId", file: "apps/server/src/modules/outbound/outbound-call.route.ts", auth: "x-api-key/session; outboundCalls:read", requestSchema: "params campaignId", responseSchema: "BatchCampaign detail", description: "Read one outbound batch campaign detail.", mappingReason: "Read-only detail." }),
  withParams({ name: "cancel_batch_campaign", kind: "tool", method: "POST", path: "/outbound-calls/batches/:campaignId/cancel", file: "apps/server/src/modules/outbound/outbound-call.route.ts", auth: "x-api-key/session; outboundCalls:delete", requestSchema: "params campaignId", responseSchema: "BatchCampaign", description: "Cancel an outbound batch campaign.", mappingReason: "Mutates/cancels campaign.", toolSchema: { campaignId: z.string().min(1) } }),
  withParams({ name: "get_outbound_call_status", kind: "resource", method: "GET", path: "/outbound-calls/:outboundId/status", file: "apps/server/src/modules/outbound/outbound-call.route.ts", auth: "x-api-key/session; outboundCalls:read", requestSchema: "params outboundId", responseSchema: "{ outboundId,status,failureReason,updatedAt }", description: "Read lightweight status for one outbound call.", mappingReason: "Read-only status." }),
  withParams({ name: "get_outbound_call", kind: "resource", method: "GET", path: "/outbound-calls/:outboundId", file: "apps/server/src/modules/outbound/outbound-call.route.ts", auth: "x-api-key/session; outboundCalls:read", requestSchema: "params outboundId", responseSchema: "OutboundCall", description: "Read one outbound call detail.", mappingReason: "Read-only detail." }),
  withParams({ name: "cancel_outbound_call", kind: "tool", method: "POST", path: "/outbound-calls/:outboundId/cancel", file: "apps/server/src/modules/outbound/outbound-call.route.ts", auth: "x-api-key/session; outboundCalls:delete", requestSchema: "params outboundId; body { reason? }", responseSchema: "OutboundCall", description: "Cancel a scheduled/running outbound call.", mappingReason: "Mutates/cancels call.", toolSchema: { outboundId: z.string().min(1), body } }),
  withParams({ name: "retry_outbound_call", kind: "tool", method: "POST", path: "/outbound-calls/:outboundId/retry", file: "apps/server/src/modules/outbound/outbound-call.route.ts", auth: "x-api-key/session; outboundCalls:create", requestSchema: "params outboundId", responseSchema: "OutboundCall", description: "Retry a failed outbound call.", mappingReason: "Triggers new call attempt.", toolSchema: { outboundId: z.string().min(1) } }),

  // Tools/secrets/widgets/admin MCP marketplace
  withParams({ name: "list_tools", kind: "resource", method: "GET", path: "/tools", file: "apps/server/src/modules/tools/tool.route.ts", auth: "x-api-key/session; tools:read", requestSchema: "none", responseSchema: "Tool[]", description: "List organization API tools available to agents.", mappingReason: "Read-only list." }),
  withParams({ name: "create_tool", kind: "tool", method: "POST", path: "/tools", file: "apps/server/src/modules/tools/tool.route.ts", auth: "x-api-key/session; tools:create", requestSchema: "body createToolSchema", responseSchema: "Tool", description: "Create an API tool an agent can call during conversations.", mappingReason: "Creates tool.", toolSchema: { body } }),
  withParams({ name: "update_tool", kind: "tool", method: "PATCH", path: "/tools/:toolId", file: "apps/server/src/modules/tools/tool.route.ts", auth: "x-api-key/session; tools:update", requestSchema: "params toolId; partial tool", responseSchema: "Tool", description: "Update an existing API tool configuration.", mappingReason: "Mutates tool.", toolSchema: { toolId: z.string().min(1), body } }),
  withParams({ name: "delete_tool", kind: "tool", method: "DELETE", path: "/tools/:toolId", file: "apps/server/src/modules/tools/tool.route.ts", auth: "x-api-key/session; tools:delete", requestSchema: "params toolId", responseSchema: "null", description: "Delete an API tool.", mappingReason: "Deletes tool.", toolSchema: { toolId: z.string().min(1) } }),
  withParams({ name: "list_agent_tools", kind: "resource", method: "GET", path: "/tools/agent/:agentId", file: "apps/server/src/modules/tools/tool.route.ts", auth: "x-api-key/session; tools:read", requestSchema: "params agentId", responseSchema: "Tool[]", description: "List tools attached to a specific agent.", mappingReason: "Read-only list." }),
  withParams({ name: "attach_tool_to_agent", kind: "tool", method: "POST", path: "/tools/:toolId/attach/:agentId", file: "apps/server/src/modules/tools/tool.route.ts", auth: "x-api-key/session; tools:update", requestSchema: "params toolId, agentId", responseSchema: "result", description: "Attach an organization API tool to an agent.", mappingReason: "Mutates agent-tool relationship.", toolSchema: { toolId: z.string().min(1), agentId: z.string().min(1) } }),
  withParams({ name: "detach_tool_from_agent", kind: "tool", method: "DELETE", path: "/tools/:toolId/detach/:agentId", file: "apps/server/src/modules/tools/tool.route.ts", auth: "x-api-key/session; tools:update", requestSchema: "params toolId, agentId", responseSchema: "result", description: "Detach an organization API tool from an agent.", mappingReason: "Mutates agent-tool relationship.", toolSchema: { toolId: z.string().min(1), agentId: z.string().min(1) } }),

  withParams({ name: "list_secrets", kind: "resource", method: "GET", path: "/secrets", file: "apps/server/src/modules/secrets/secret.route.ts", auth: "x-api-key/session; secrets:read", requestSchema: "none", responseSchema: "Secret[] redacted", description: "List redacted secrets stored for the organization.", mappingReason: "Read-only list." }),
  withParams({ name: "create_secret", kind: "tool", method: "POST", path: "/secrets", file: "apps/server/src/modules/secrets/secret.route.ts", auth: "x-api-key/session; secrets:create", requestSchema: "body { name, value }", responseSchema: "Secret redacted", description: "Create a secret value for webhook/tool configuration.", mappingReason: "Creates secret.", toolSchema: { body } }),
  withParams({ name: "delete_secret", kind: "tool", method: "DELETE", path: "/secrets/:secretId", file: "apps/server/src/modules/secrets/secret.route.ts", auth: "x-api-key/session; secrets:delete", requestSchema: "params secretId", responseSchema: "null", description: "Delete a stored secret by id.", mappingReason: "Deletes secret.", toolSchema: { secretId: z.string().min(1) } }),

  withParams({ name: "list_agent_widgets", kind: "resource", method: "GET", path: "/agents/:agentId/widgets", file: "apps/server/src/modules/widgets/widget.route.ts", auth: "x-api-key/session; agentWidget:read", requestSchema: "params agentId", responseSchema: "AgentWidget[]", description: "List website widgets for one agent.", mappingReason: "Read-only list." }),
  withParams({ name: "create_agent_widget", kind: "tool", method: "POST", path: "/agents/:agentId/widgets", file: "apps/server/src/modules/widgets/widget.route.ts", auth: "x-api-key/session; agentWidget:create", requestSchema: "params agentId; body createAgentWidgetSchema", responseSchema: "AgentWidget", description: "Create a public website voice widget for an agent.", mappingReason: "Creates widget.", toolSchema: { agentId: z.string().min(1), body } }),
  withParams({ name: "get_agent_widget", kind: "resource", method: "GET", path: "/widgets/:widgetId", file: "apps/server/src/modules/widgets/widget.route.ts", auth: "x-api-key/session; agentWidget:read", requestSchema: "params widgetId", responseSchema: "AgentWidget", description: "Read one website widget configuration.", mappingReason: "Read-only detail." }),
  withParams({ name: "update_agent_widget", kind: "tool", method: "PATCH", path: "/widgets/:widgetId", file: "apps/server/src/modules/widgets/widget.route.ts", auth: "x-api-key/session; agentWidget:update", requestSchema: "params widgetId; partial createAgentWidgetSchema", responseSchema: "AgentWidget", description: "Update a website widget configuration including theme, origin allowlist, consent, and enabled state.", mappingReason: "Mutates widget.", toolSchema: { widgetId: z.string().min(1), body } }),
  withParams({ name: "delete_agent_widget", kind: "tool", method: "DELETE", path: "/widgets/:widgetId", file: "apps/server/src/modules/widgets/widget.route.ts", auth: "x-api-key/session; agentWidget:delete", requestSchema: "params widgetId", responseSchema: "null", description: "Delete a website widget.", mappingReason: "Deletes widget.", toolSchema: { widgetId: z.string().min(1) } }),

  // Existing MCP connection APIs
  withParams({ name: "list_mcp_catalog", kind: "resource", method: "GET", path: "/mcp/catalog", file: "apps/server/src/modules/mcp/mcp.route.ts", auth: "x-api-key/session; tools:read", requestSchema: "query { page?, pageSize?, search?, verified?, sort? }", responseSchema: "MCP catalog", description: "List curated/custom MCP servers available to connect.", mappingReason: "Read-only catalog.", queryKeys: ["page", "pageSize", "search", "verified", "sort"] }),
  withParams({ name: "list_mcp_connections", kind: "resource", method: "GET", path: "/mcp/connections", file: "apps/server/src/modules/mcp/mcp.route.ts", auth: "x-api-key/session; tools:read", requestSchema: "none", responseSchema: "McpConnection[]", description: "List connected remote MCP servers.", mappingReason: "Read-only list." }),
  withParams({ name: "connect_mcp_server", kind: "tool", method: "POST", path: "/mcp/connections", file: "apps/server/src/modules/mcp/mcp.route.ts", auth: "x-api-key/session; tools:create", requestSchema: "body { catalogSlug xor customUrl, displayName? }", responseSchema: "McpConnection", description: "Connect a new remote MCP server from catalog or custom URL.", mappingReason: "Creates connection.", toolSchema: { body } }),
  withParams({ name: "refresh_mcp_connection", kind: "tool", method: "POST", path: "/mcp/connections/:mcpConnectionId/refresh", file: "apps/server/src/modules/mcp/mcp.route.ts", auth: "x-api-key/session; tools:update", requestSchema: "params mcpConnectionId", responseSchema: "McpConnection", description: "Refresh tool metadata/status for a connected MCP server.", mappingReason: "Triggers refresh.", toolSchema: { mcpConnectionId: z.string().min(1) } }),
  withParams({ name: "disconnect_mcp_connection", kind: "tool", method: "DELETE", path: "/mcp/connections/:mcpConnectionId", file: "apps/server/src/modules/mcp/mcp.route.ts", auth: "x-api-key/session; tools:delete", requestSchema: "params mcpConnectionId", responseSchema: "null", description: "Disconnect a remote MCP server.", mappingReason: "Deletes connection.", toolSchema: { mcpConnectionId: z.string().min(1) } }),
  withParams({ name: "list_agent_mcp_connections", kind: "resource", method: "GET", path: "/mcp/agent/:agentId", file: "apps/server/src/modules/mcp/mcp.route.ts", auth: "x-api-key/session; tools:read", requestSchema: "params agentId", responseSchema: "McpConnection[]", description: "List MCP connections attached to an agent.", mappingReason: "Read-only list." }),
  withParams({ name: "attach_mcp_connection_to_agent", kind: "tool", method: "POST", path: "/mcp/connections/:mcpConnectionId/attach/:agentId", file: "apps/server/src/modules/mcp/mcp.route.ts", auth: "x-api-key/session; tools:update", requestSchema: "params mcpConnectionId, agentId; body { enabled? }", responseSchema: "result", description: "Attach a connected MCP server to an agent.", mappingReason: "Mutates relationship.", toolSchema: { mcpConnectionId: z.string().min(1), agentId: z.string().min(1), body } }),
  withParams({ name: "detach_mcp_connection_from_agent", kind: "tool", method: "DELETE", path: "/mcp/connections/:mcpConnectionId/detach/:agentId", file: "apps/server/src/modules/mcp/mcp.route.ts", auth: "x-api-key/session; tools:update", requestSchema: "params mcpConnectionId, agentId", responseSchema: "null", description: "Detach a connected MCP server from an agent.", mappingReason: "Mutates relationship.", toolSchema: { mcpConnectionId: z.string().min(1), agentId: z.string().min(1) } }),
  withParams({ name: "execute_connected_mcp_tool", kind: "tool", method: "POST", path: "/mcp/connections/:mcpConnectionId/tools/:toolName/execute", file: "apps/server/src/modules/mcp/mcp.route.ts", auth: "x-api-key/session; tools:read", requestSchema: "params mcpConnectionId, toolName; body { agentId?, callId?, arguments }", responseSchema: "tool result", description: "Execute a tool on a connected remote MCP server through QuickVoice.", mappingReason: "Executes remote action.", toolSchema: { mcpConnectionId: z.string().min(1), toolName: z.string().min(1), body } }),

  // Excluded APIs
  withParams({ name: "ingest_call_log", kind: "excluded", method: "POST", path: "/calls", file: "apps/server/src/modules/calllogs/calllog.route.ts", auth: "internal bearer only", requestSchema: "callLogSchema", responseSchema: "CallLog", description: "Internal LiveKit/AI call-log ingestion.", mappingReason: "Excluded", excludedReason: "Internal-only server-to-server ingest; unsafe to expose to external MCP clients." }),
  withParams({ name: "get_agent_internal_config", kind: "excluded", method: "GET", path: "/agents/internal-config/:agentId", file: "apps/server/src/modules/agent/agent.route.ts", auth: "internal bearer only", requestSchema: "params agentId", responseSchema: "runtime config", description: "Internal runtime config lookup.", mappingReason: "Excluded", excludedReason: "Internal runtime API requiring INTERNAL_API_KEY." }),
  withParams({ name: "get_agent_number_config", kind: "excluded", method: "GET", path: "/agents/number-config/:phoneNumber", file: "apps/server/src/modules/agent/agent.route.ts", auth: "internal bearer only", requestSchema: "params phoneNumber", responseSchema: "runtime config", description: "Internal runtime config lookup by phone number.", mappingReason: "Excluded", excludedReason: "Internal runtime API requiring INTERNAL_API_KEY." }),
  withParams({ name: "public_widget_config", kind: "excluded", method: "GET", path: "/public/widgets/:widgetId/config", file: "apps/server/src/modules/widgets/widget.route.ts", auth: "public CORS origin allowlist", requestSchema: "params widgetId + Origin", responseSchema: "PublicWidgetConfig", description: "Public website widget config.", mappingReason: "Excluded", excludedReason: "Public browser widget API with origin-based CORS, not organization API-key MCP surface." }),
  withParams({ name: "public_widget_session", kind: "excluded", method: "POST", path: "/public/widgets/:widgetId/sessions", file: "apps/server/src/modules/widgets/widget.route.ts", auth: "public CORS origin allowlist", requestSchema: "CreatePublicWidgetSessionInput", responseSchema: "PublicWidgetSession", description: "Public website widget LiveKit session creation.", mappingReason: "Excluded", excludedReason: "Public browser call entrypoint; MCP should use admin widget APIs, not impersonate website visitors." }),
  withParams({ name: "public_widget_end_session", kind: "excluded", method: "POST", path: "/public/widgets/:widgetId/sessions/:sessionId/end", file: "apps/server/src/modules/widgets/widget.route.ts", auth: "public endToken + CORS", requestSchema: "endToken", responseSchema: "ended", description: "Public widget session cleanup.", mappingReason: "Excluded", excludedReason: "Tied to browser session endToken, not a general MCP API." }),
  withParams({ name: "better_auth_routes", kind: "excluded", method: "POST", path: "/auth/*", file: "apps/server/src/index.ts", auth: "better-auth", requestSchema: "better-auth managed", responseSchema: "better-auth managed", description: "Better Auth generated auth routes.", mappingReason: "Excluded", excludedReason: "Generated auth surface; not wrapped as domain MCP tools." }),
  withParams({ name: "api_docs", kind: "excluded", method: "GET", path: "/docs /docs.json", file: "apps/server/src/index.ts", auth: "none", requestSchema: "none", responseSchema: "Swagger UI/spec", description: "API documentation endpoints.", mappingReason: "Excluded", excludedReason: "Documentation/static UI, not a domain API tool/resource." }),
  withParams({ name: "ai_internal_api", kind: "excluded", method: "POST", path: "AI app /health, /agents/{id}/config, /voice/*, /kb/*", file: "apps/ai/api.py", auth: "x-internal-key", requestSchema: "FastAPI/Pydantic", responseSchema: "runtime responses", description: "AI runtime internal APIs.", mappingReason: "Excluded", excludedReason: "Internal server-to-server AI runtime APIs; they are consumed by QuickVoice API and should not be exposed directly over MCP." }),
];

export const exposedDefinitions = apiDefinitions.filter((definition) => definition.kind !== "excluded");
export const resourceDefinitions = exposedDefinitions.filter((definition) => definition.kind === "resource");
export const toolDefinitions = exposedDefinitions.filter((definition) => definition.kind === "tool");
export const excludedDefinitions = apiDefinitions.filter((definition) => definition.kind === "excluded");
