<<<<<<< HEAD
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  excludedDefinitions,
  resourceDefinitions,
  toolDefinitions,
} from "../../mcp-server/src/api-registry.js";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const target = resolve(scriptDir, "../src/generated/mcp-reference.ts");
mkdirSync(dirname(target), { recursive: true });

const serialize = (value: unknown) => JSON.stringify(value, null, 2);
const compactTool = (item: (typeof toolDefinitions)[number]) => ({
  name: item.name,
  method: item.method,
  path: item.path,
  auth: item.auth,
  description: item.description,
  requestSchema: item.requestSchema,
  responseSchema: item.responseSchema,
  file: item.file,
  mappingReason: item.mappingReason,
  risk: riskFor(item.name, item.description),
});
const compactResource = (item: (typeof resourceDefinitions)[number]) => ({
  name: item.name,
  method: item.method,
  path: item.path,
  auth: item.auth,
  description: item.description,
  requestSchema: item.requestSchema,
  responseSchema: item.responseSchema,
  file: item.file,
  mappingReason: item.mappingReason,
  uri: resourceUri(item),
});
const compactExcluded = (item: (typeof excludedDefinitions)[number]) => ({
  name: item.name,
  method: item.method,
  path: item.path,
  auth: item.auth,
  description: item.description,
  file: item.file,
  excludedReason: item.excludedReason ?? "Excluded from public MCP surface.",
});

function resourceUri(item: (typeof resourceDefinitions)[number]) {
  return item.params?.length
    ? `quickvoice://${item.name}/${item.params.map((param) => `{${param}}`).join("/")}`
    : `quickvoice://${item.name}`;
}

function riskFor(name: string, description: string) {
  const text = `${name} ${description}`.toLowerCase();
  if (text.includes("buy") || text.includes("outbound") || text.includes("call")) {
    return "external-cost";
  }
  if (text.includes("delete") || text.includes("cancel") || text.includes("end")) {
    return "destructive";
  }
  if (text.includes("create") || text.includes("update") || text.includes("save") || text.includes("attach") || text.includes("disconnect")) {
    return "write";
  }
  return "read";
}

const source = `// Generated by apps/docs/scripts/generate-mcp-reference.ts. Do not edit manually.\n\nexport const mcpTools = ${serialize(toolDefinitions.map(compactTool))} as const;\n\nexport const mcpResources = ${serialize(resourceDefinitions.map(compactResource))} as const;\n\nexport const mcpExcludedApis = ${serialize(excludedDefinitions.map(compactExcluded))} as const;\n\nexport const mcpReferenceStats = {\n  toolCount: ${toolDefinitions.length},\n  resourceCount: ${resourceDefinitions.length},\n  excludedCount: ${excludedDefinitions.length},\n} as const;\n`;

writeFileSync(target, source);
console.log(`Generated ${target}`);
console.log(`MCP reference: ${toolDefinitions.length} tools, ${resourceDefinitions.length} resources, ${excludedDefinitions.length} excluded APIs`);
=======
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  excludedDefinitions,
  resourceDefinitions,
  toolDefinitions,
} from "../../mcp-server/src/api-registry.js";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const target = resolve(scriptDir, "../src/generated/mcp-reference.ts");
mkdirSync(dirname(target), { recursive: true });

const serialize = (value: unknown) => JSON.stringify(value, null, 2);
const compactTool = (item: (typeof toolDefinitions)[number]) => ({
  name: item.name,
  method: item.method,
  path: item.path,
  auth: item.auth,
  description: item.description,
  requestSchema: item.requestSchema,
  responseSchema: item.responseSchema,
  file: item.file,
  mappingReason: item.mappingReason,
  risk: riskFor(item.name, item.description),
});
const compactResource = (item: (typeof resourceDefinitions)[number]) => ({
  name: item.name,
  method: item.method,
  path: item.path,
  auth: item.auth,
  description: item.description,
  requestSchema: item.requestSchema,
  responseSchema: item.responseSchema,
  file: item.file,
  mappingReason: item.mappingReason,
  uri: resourceUri(item),
});
const compactExcluded = (item: (typeof excludedDefinitions)[number]) => ({
  name: item.name,
  method: item.method,
  path: item.path,
  auth: item.auth,
  description: item.description,
  file: item.file,
  excludedReason: item.excludedReason ?? "Excluded from public MCP surface.",
});

function resourceUri(item: (typeof resourceDefinitions)[number]) {
  return item.params?.length
    ? `quickvoice://${item.name}/${item.params.map((param) => `{${param}}`).join("/")}`
    : `quickvoice://${item.name}`;
}

function riskFor(name: string, description: string) {
  const text = `${name} ${description}`.toLowerCase();
  if (text.includes("buy") || text.includes("outbound") || text.includes("call")) {
    return "external-cost";
  }
  if (text.includes("delete") || text.includes("cancel") || text.includes("end")) {
    return "destructive";
  }
  if (text.includes("create") || text.includes("update") || text.includes("save") || text.includes("attach") || text.includes("disconnect")) {
    return "write";
  }
  return "read";
}

const source = `// Generated by apps/docs/scripts/generate-mcp-reference.ts. Do not edit manually.\n\nexport const mcpTools = ${serialize(toolDefinitions.map(compactTool))} as const;\n\nexport const mcpResources = ${serialize(resourceDefinitions.map(compactResource))} as const;\n\nexport const mcpExcludedApis = ${serialize(excludedDefinitions.map(compactExcluded))} as const;\n\nexport const mcpReferenceStats = {\n  toolCount: ${toolDefinitions.length},\n  resourceCount: ${resourceDefinitions.length},\n  excludedCount: ${excludedDefinitions.length},\n} as const;\n`;

writeFileSync(target, source);
console.log(`Generated ${target}`);
console.log(`MCP reference: ${toolDefinitions.length} tools, ${resourceDefinitions.length} resources, ${excludedDefinitions.length} excluded APIs`);
>>>>>>> origin/main
