<<<<<<< HEAD
[project]
  subdomain = "quickintell-pemnve31"

[agent]
  id = "CA_CBhKMxKQvaAJ"
=======
[project]
  subdomain = "quickintell-pemnve31"

[agent]
  id = "CA_CBhKMxKQvaAJ"
>>>>>>> origin/main
